### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by jlaporte44** [jaredhobbs/rocky-mountain-power#3]
I'm not great with home assistant but I cannot get it the add-on to read my bill. 2 FA is not activated. I opened my firewall. Here is the error log:

This error originated from a custom integration.

Logger: custom_components.rocky_mountain_power.coordinator
Source: helpers/update_coordinator.py:312
integration: Rocky Mountain Power (documentation, issues)
First occurred: June 21, 2024 at 7:50:06 PM (87 occurrences)
Last logged: 8:04:44 AM

Unexpected error fetching Rocky Mountain Power data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rocky_mountain_power/coordinator.py", line 76, in _async_update_data
    forecasts: list[Forecast] = await self.hass.async_add_executor_job(self.api.get_forecast)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rocky_mountain_power/rocky_mountain_power.py", line 478, in get_forecast
    self.utility.get_forecast()
  File "/config/custom_components/rocky_mountain_power/rocky_mountain_power.py", line 185, in get_forecast
    self.goto_energy_usage()
  File "/config/custom_components/rocky_mountain_power/rocky_mountain_power.py", line 176, in goto_energy_usage
    target = self.get_el(By.LINK_TEXT, "Energy usage")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rocky_mountain_power/rocky_mountain_power.py", line 50, in get_el
    el = func(by, val)
         ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Energy usage"}
  (Session info: chrome=126.0.6478.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x560e985c069a <unknown>
#1 0x560e982a30dc <unknown>
#2 0x560e982ef931 <unknown>
#3 0x560e982efa21 <unknown>
#4 0x560e98334234 <unknown>
#5 0x560e9831289d <unknown>
#6 0x560e983315c3 <unknown>
#7 0x560e98312613 <unknown>
#8 0x560e982e24f7 <unknown>
#9 0x560e982e2e4e <unknown>
#10 0x560e9858686b <unknown>
#11 0x560e9858a911 <unknown>
#12 0x560e9857235e <unknown>
#13 0x560e9858b472 <unknown>
#14 0x560e98556cbf <unknown>
#15 0x560e985b0098 <unknown>
#16 0x560e985b0270 <unknown>
#17 0x560e985bf7cc <unknown>
#18 0x7fa58b6cbac3 <unknown>

**Comment by jgrudolph** [comment]
Just installed and am getting the exact same error.

**Comment by bmatheny** [comment]
This is fixed in PR #5
